### ISSUE TITLE
Issue running "run_due" notebook

### ISSUE THREAD

**Issue by mohanrajroboticist** [orientino/dum-components#1]
The following error occurs when I follow the procedure in the read me

<img width="1075" alt="Screenshot 2023-06-15 at 09 55 57" src="https://github.com/orientino/dum-components/assets/86923487/4d14fda9-d6b4-4bc3-8fe4-f54e3e64caac">

**Comment by orientino** [comment]
Thanks for reporting the issue, it should work now
